### ISSUE TITLE
love-release not packing everything in project directory

### ISSUE THREAD

**Issue by videah** [MisterDA/love-release#36] opened 2016-04-09 23:12 UTC
![](https://i.imgur.com/lkMuLMa.png)

For some reason, only my font folder, conf.lua, and my readme gets packed.
Any reason this is happening?

**Comment by MisterDA** [comment] 2016-04-10 21:12
I have stumbled upon this once too, but I wasn't able to identify the causes of this error. I'll try to fix this.

**Comment by Positive07** [comment] 2016-04-11 17:17
Would you please check the return value of `fs.pop_dir`

I think it may stay in that directory for ever

Also changing the current directory like that inside the loop may destroy the iterator

Considerar saving all the folder names and after the whole folder was iterated, iterate on the next one

These are just suggestions not tested and not proved to work, but some ideas that may help debug this. Cheers

**Comment by MisterDA** [comment] 2016-04-12 11:35
[`fs.pop_dir`](https://github.com/keplerproject/luarocks/blob/master/src/luarocks/fs/lua.lua#L240) returns true if a pop ocurred, false if the stack was empty.

Thanks for the suggestions :)

Debug all the things !

**Comment by Positive07** [comment] 2017-05-19 06:40
Try something like this:
```lua
local _buildFileTree
_buildFileTree = function(dir)
  local subDirs = {}

  for file in assert(fs.dir()) do
    if not file:find("^%.git") then
      if fs.is_dir(file) then
        subDirs[#subDirs + 1] = file
      elseif fs.is_file(file) then
        dir[#dir+1] = file
      end
    end
  end

  for _, path in ipairs(subDirs) do
    local newDir = {}
    dir[path] = newDir
    assert(fs.change_dir(path))
    _buildFileTree(newDir)
    assert(fs.pop_dir())
  end
end
```

This has the overhead of needing a secondary loop but will probably work more reliably.

You have to consider that `fs.dir` returns an iterator based on a `coroutine` and Lua is not that good with coroutines, and handling multiple coroutines at once, switching between them and so on...

**Comment by Positive07** [comment] 2017-05-19 17:12
This should be fixed now 👍

**Closed** 2018-04-20 20:37 UTC
